import test from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { createServer as createNetServer } from 'node:net';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';

test('actual TerminalView renders isolated tmux and sends terminal query replies', { skip: process.env.GOOESHELL_RENDER_WSL_TEST === '1' ? false : 'Set GOOESHELL_RENDER_WSL_TEST=1 with Electron, built main, Ubuntu-24.04 and tmux installed', timeout: 65_000 }, async t => {
  const root = process.cwd();
  const artifacts = await fs.mkdtemp(path.resolve('../.build/terminal-render-'));
  const report = path.join(artifacts, 'result.json');
  const reservation = createNetServer();
  await new Promise<void>(resolve => reservation.listen(0, '127.0.0.1', resolve));
  const port = (reservation.address() as { port: number }).port;
  await new Promise<void>(resolve => reservation.close(() => resolve()));
  const vite = await createServer({ configFile: false, root, cacheDir: path.join(artifacts, 'vite-cache'), plugins: [react()], resolve: { alias: [{ find: /^@xterm\/xterm$/, replacement: path.join(root, 'tests/fixtures/xterm-observed.ts') }] }, server: { host: '127.0.0.1', port, strictPort: true, hmr: false } });
  await vite.listen();
  t.after(() => vite.close());
  const address = vite.httpServer!.address() as { port: number };
  const env = { ...process.env, GOOESHELL_RENDER_URL: `http://127.0.0.1:${address.port}/tests/fixtures/terminal-render.html`, GOOESHELL_RENDER_REPORT: report, GOOESHELL_RENDER_DATA: path.join(artifacts, 'user-data') };
  delete env.ELECTRON_RUN_AS_NODE;
  const child = spawn(path.join(root, 'node_modules/electron/dist/electron.exe'), [path.join(root, 'tests/fixtures/terminal-render-electron.cjs')], { env, cwd: root, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
  let stderr = '';
  child.stderr.on('data', data => { stderr += data.toString(); });
  child.stdout.on('data', () => {});
  const timeout = setTimeout(() => child.kill(), 55_000);
  timeout.unref();
  child.once('close', () => clearTimeout(timeout));
  t.after(() => { if (child.exitCode === null) child.kill(); });
  const exit = await new Promise<number | null>((resolve, reject) => { child.once('close', resolve); child.once('error', reject); });
  const result = JSON.parse(await fs.readFile(report, 'utf8').catch(() => { throw new Error(`No renderer report: ${stderr}`); }));
  t.diagnostic(`render artifacts: ${artifacts}`);
  assert.equal(exit, 0, JSON.stringify(result, null, 2) + stderr);
  assert.equal(result.success, true);
  assert.equal(result.queries.length, 3);
  assert.equal(result.acked, result.bytes);
  assert.match(result.after.text, /RENDER_STILL_RESPONSIVE/);
});
